### ISSUE TITLE
Error creating firewall:

### ISSUE THREAD

**Issue by billcarroll** [colinwilson/example-terraform-modules#1]
Was just following your tutorial "[Deploy a HA K3s Cluster on DigitalOcean in 10 minutes using Terraform](https://colinwilson.uk/2021/04/04/deploy-a-ha-k3s-cluster-on-digitalocean-in-10-minutes-using-terraform/)" 

Ran into this error during `terraform apply` and thought I'd drop it here for you. Thanks for your work on the tutorial, it's very helpful.

│ Error: Error creating firewall: POST https://api.digitalocean.com/v2/firewalls: 422 (request "e6a333b8-0887-43a2-aff0-540d6b931e2f") tag k3s_server does not exist
│
│   with module.ha-k3s.digitalocean_firewall.k3s_firewall,
│   on .terraform/modules/ha-k3s/firewall.tf line 10, in resource "digitalocean_firewall" "k3s_firewall":
│   10: resource "digitalocean_firewall" "k3s_firewall" {

**Comment by colinwilson** [comment]
Thank you for letting me know 👍. I'll issue an update/fix to the module as soon as I get the chance.

**Comment by colinwilson** [comment]
Fixed in new release, [0.2.3](https://github.com/aigisuk/terraform-digitalocean-ha-k3s/releases/tag/0.2.3) ✌
